<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LT8304" failures="1" tests="4" name="Test" time="11.547" errors="0" timestamp="2025-07-08T13:36:52 IST">
  <testcase classname="api.test.StoreTests1" name="testPostStore" time="5.703"/>
  <testcase classname="api.test.StoreTests1" name="testGetOrderByOrderId" time="1.748"/>
  <testcase classname="api.test.StoreTests1" name="testGetStoreInventory" time="1.449"/>
  <testcase classname="api.test.StoreTests1" name="testDeleteOrderByOrderId" time="1.458">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTests1.testDeleteOrderByOrderId(StoreTests1.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteOrderByOrderId -->
</testsuite> <!-- Test -->
