<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="7" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-08T17:33:03 IST" name="Default suite" finished-at="2025-07-08T17:33:21 IST" duration-ms="17988">
    <groups>
    </groups>
    <test started-at="2025-07-08T17:33:03 IST" name="Default test" finished-at="2025-07-08T17:33:21 IST" duration-ms="17988">
      <class name="api.test.StoreDataDrivenTests">
        <test-method signature="testPostStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:04 IST" name="testPostStore" data-provider="StoreData" finished-at="2025-07-08T17:33:09 IST" duration-ms="4368" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[101]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2025-06-30T06:40:12.349Z]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[placed]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostStore -->
        <test-method signature="testPostStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:09 IST" name="testPostStore" data-provider="StoreData" finished-at="2025-07-08T17:33:10 IST" duration-ms="1405" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[102]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2025-07-01T06:40:12.349Z]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[misplaced]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[FALSE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostStore -->
        <test-method signature="testPostStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:10 IST" name="testPostStore" data-provider="StoreData" finished-at="2025-07-08T17:33:12 IST" duration-ms="1519" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[103]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2025-07-02T06:40:12.349Z]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[cancelled]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostStore -->
        <test-method signature="testDeleteOrder(java.lang.String)[pri:2, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:12 IST" name="testDeleteOrder" data-provider="OrderId" finished-at="2025-07-08T17:33:14 IST" duration-ms="1465" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[101]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteOrder -->
        <test-method signature="testDeleteOrder(java.lang.String)[pri:2, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:14 IST" name="testDeleteOrder" data-provider="OrderId" finished-at="2025-07-08T17:33:15 IST" duration-ms="1311" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[102]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteOrder -->
        <test-method signature="testDeleteOrder(java.lang.String)[pri:2, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:15 IST" name="testDeleteOrder" data-provider="OrderId" finished-at="2025-07-08T17:33:16 IST" duration-ms="1586" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[103]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteOrder -->
        <test-method signature="testGetOrderById(java.lang.String)[pri:2, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:17 IST" name="testGetOrderById" data-provider="OrderId" finished-at="2025-07-08T17:33:18 IST" duration-ms="1371" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[101]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetOrderById -->
        <test-method signature="testGetOrderById(java.lang.String)[pri:2, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:18 IST" name="testGetOrderById" data-provider="OrderId" finished-at="2025-07-08T17:33:19 IST" duration-ms="1403" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[102]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.test.StoreDataDrivenTests.testGetOrderById(StoreDataDrivenTests.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetOrderById -->
        <test-method signature="testGetOrderById(java.lang.String)[pri:2, instance:api.test.StoreDataDrivenTests@6aeb35e6]" started-at="2025-07-08T17:33:19 IST" name="testGetOrderById" data-provider="OrderId" finished-at="2025-07-08T17:33:21 IST" duration-ms="1474" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[103]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.test.StoreDataDrivenTests.testGetOrderById(StoreDataDrivenTests.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetOrderById -->
      </class> <!-- api.test.StoreDataDrivenTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
